name: dinov2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pytorch::pytorch>=2.0.0
  - pytorch::pytorch-cuda=>11.7.0
  - pytorch::torchvision>=0.15.0
  - omegaconf
  - torchmetrics>=0.10.3
  - fvcore
  - iopath
  - conda-forge::xformers
  - conda-forge::pydensecrf
  - pip
  - pip:
    - ipykernel==6.26.0
    - matplotlib==3.8.1
    - scikit-image==0.22.0
    - scikit-learn==1.3.1
    - av==10.0.0
    - timm
    - skops
